name: wdm
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10.13
  - numpy=1.26.4
  - pytorch=2.2.0=py3.10_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8
  - pywavelets=1.4.1
  - scipy=1.12.0
  - torchaudio=2.2.0=py310_cu118
  - torchvision=0.17.0=py310_cu118
  - pip
  - pip:
    - nibabel==5.2.0
    - blobfile==2.1.1
    - tensorboard==2.16.2
    - matplotlib==3.8.3
    - tqdm==4.66.2
    - dicom2nifti==2.4.10
